# Generated by Django 2.0.13 on 2019-03-19 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelshare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotelshare.Request'),
        ),
    ]
