# Generated by Django 2.0.13 on 2019-03-19 14:04

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hotelshare', '0002_auto_20190319_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2019, 3, 19, 14, 4, 1, 640871, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2019, 3, 19, 14, 4, 10, 529024, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='checkin',
            field=models.DateField(default=datetime.datetime(2019, 3, 19, 14, 4, 19, 328807, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='checkout',
            field=models.DateField(default=datetime.datetime(2019, 3, 19, 14, 4, 25, 504622, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelshare.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.DateField(),
        ),
    ]
