# Generated by Django 2.0.13 on 2019-03-19 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelshare', '0004_auto_20190319_1121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'verbose_name': 'Hotel', 'verbose_name_plural': 'Hoteis'},
        ),
        migrations.AlterModelOptions(
            name='local',
            options={'verbose_name': 'Local', 'verbose_name_plural': 'Locais'},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name': 'Combinação', 'verbose_name_plural': 'Combinações'},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
    ]
