# Generated by Django 2.0.13 on 2019-03-19 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelshare', '0005_auto_20190319_1125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'verbose_name': 'Hotél', 'verbose_name_plural': 'Hoteis'},
        ),
    ]
