# Generated by Django 2.0.13 on 2019-03-21 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelshare', '0006_auto_20190319_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='age',
            new_name='birthday',
        ),
    ]
