# Generated by Django 2.0.13 on 2019-03-21 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelshare', '0008_auto_20190321_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelshare.Local'),
        ),
    ]
