# Generated by Django 2.0.13 on 2019-03-21 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelshare', '0009_auto_20190321_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='event',
            name='request',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='request',
            name='local',
        ),
    ]
