# Generated by Django 2.0.13 on 2019-03-21 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelshare', '0013_hotel_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='adress',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hotelshare.Local'),
        ),
    ]
